/* tslint:disable */
/* eslint-disable */
/**
 * CMS APIs
 * The CMS APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ex1
 */
export interface Ex1 {
    /**
     * The unique identification integer
     * @type {string}
     * @memberof Ex1
     */
    id: string;
    /**
     * The unique identification integer
     * @type {string}
     * @memberof Ex1
     */
    name: string;
}

/**
 * Check if a given object implements the Ex1 interface.
 */
export function instanceOfEx1(value: object): value is Ex1 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function Ex1FromJSON(json: any): Ex1 {
    return Ex1FromJSONTyped(json, false);
}

export function Ex1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Ex1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function Ex1ToJSON(json: any): Ex1 {
    return Ex1ToJSONTyped(json, false);
}

export function Ex1ToJSONTyped(value?: Ex1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

