/* tslint:disable */
/* eslint-disable */
/**
 * CMS APIs
 * The CMS APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Ex1,
    Ex1FromJSON,
    Ex1ToJSON,
} from '../models/Ex1';

/**
 * 
 */
export class AppApi extends runtime.BaseAPI {

    /**
     * Creates request options for appControllerGetRandomName without sending the request
     */
    async appControllerGetRandomNameRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async appControllerGetRandomNameRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ex1>> {
        const requestOptions = await this.appControllerGetRandomNameRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ex1FromJSON(jsonValue));
    }

    /**
     */
    async appControllerGetRandomName(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ex1> {
        const response = await this.appControllerGetRandomNameRaw(initOverrides);
        return await response.value();
    }

}
